baseURL = "https://blog.ftchen.site/"
languageCode = "en-us"
title = "FtChen's Site"
theme = "dream"

defaultContentLanguage = "en"

disqusShortname = "ftchen93-github-io"

[params]
   # dark mode
    defaultDark = false
    backgroundDark = "black"
    backgroundImageDark = "/me/background-dark.jpg"
    darkLinkColor = "darkseagreen"
    darkNav = true
    dark404 = true

    author = "FtChen"
    # description = ""
    # avatar = "/img/avatar.jpg"
    # headerTitle = ""
    # motto = "Motto"

    email = "funtat.chen@gmail.com"
  # twitter = ""
    facebook = "FunTatChen"
    instagram = "ftchen"
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  # search
  enableSearch = true

   # options
  showSummaryCoverInPost = true